import Head from "next/head";
import { Categories, PostCard, PostWidget } from "components";
import { getPosts } from "services";
import React from "react";

// const posts = [
//   {
//     name: "Mern Stack",
//     excerpt: "Mern Stack MongoDB, ExpressJS, ReactJS, NodeJS",
//   },
//   {
//     name: "Social Media",
//     excerpt: "Telegram, Instagram, Facebook, ADS",
//   },
// ];

export default function Home({ posts }) {
  return (
    <React.Fragment>
      <div className="bg-slate-900 container mx-auto px-10 mb-8">
        <Head>
          <title>ZakBlog NextJS</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="bg-slate-800 container mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 p-8 rounded-lg">
          <div className="lg:col-span-4 col-span-1">
            <div className="lg:sticky relative top-8">
              <PostWidget categories={["blog"]} />
              <Categories />
            </div>
          </div>
          <div className="lg:col-span-8 col-span-1">
            {posts.map((post, index) => (
              <PostCard key={index} post={post.node} />
            ))}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: { posts },
  };
}
